#!/bin/sh

LANG=lang
HOST=localhost
PORT=1234

FILE1=/tmp/lang1-$$
FILE2=/tmp/lang2-$$
ERROR=/tmp/lang-err-$$
FILTER=/tmp/lang-$$

GETTEXT="gettext -d lang_ui"

curl -s "http://semes-olla.rhcloud.com/words?Swadesh/English.py" | paste -----> $FILTER
 
if [ -r ~/.lang.conf ]
then
	. ~/.lang.conf
elif [ -r /etc/lang.conf ]
then
	. /etc/lang.conf
fi

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

help () {
        echo "Usage: $0 [ host [port] | --help ]"
}

end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
}

if [ $# -eq 1 ]
then
        if [ $1 -eq '--help' ]
        then
                help
                exit -1
        else
                HOST=$1
        fi
elif [ $# -eq 2 ]
then
        PORT=$2
fi

if [ $# -ge 1 -o `basename $0` = 'nlang_ui' ]
then
	if [ $HOST -a $PORT ]
	then
	        CALC="nc $HOST $PORT"
	else
		echo "You must set HOST and PORT"
		exit -2
	fi
fi

while true
do
	$DIALOG --inputbox "`$GETTEXT \"Enter number:\"`" 8 35 2> $FILE1 || end
	curl -s "http://semes-olla.rhcloud.com/words?`cat $FILE1`&Swadesh/Albanian.py" > $FILE2
	
	cat $FILE2
	
	if cat $FILE1 | $CALC > $FILE2 2>$ERROR
	then
		MSG="`$GETTEXT \"Translated word:\"` `cat $FILE2`\\n\\n`$GETTEXT \"Continue?\"`"
		$DIALOG --yesno "$MSG" 7 20 || end
	else
		MSG="`$GETTEXT \"Error:\"`\\n\\n`cat $ERROR`\\n\\n`$GETTEXT \"Continue?\"`"
		$DIALOG --yesno "$MSG" 10 35 || end
	fi
done
